import random
import logging
from datetime import datetime
from typing import Tuple, Optional
import json

from agents.base_agent import BaseAgent

from utils.logger import setup_logger
logger = setup_logger(__name__)

class ContentAgent(BaseAgent):
    """Agent for generating article content"""
    
    def __init__(self, llm_manager=None):
        super().__init__("A1_content_agent", llm_manager)
        self.topics = [
            "Artificial Intelligence", "Machine Learning", "Data Science",
            "Programming", "Software Development", "Technology Trends",
            "Web Development", "Cloud Computing", "Cybersecurity",
            "Blockchain Technology", "Internet of Things", "Quantum Computing"
        ]
    
    def _setup(self):
        """Setup content agent"""
        self.logger.info(f"Content agent initialized with {len(self.topics)} topics")
    
    def _generate_topic(self) -> str:
        """Generate or select a topic"""
        return random.choice(self.topics)
    
    async def execute(self) -> Tuple[Optional[str], Optional[str]]:
        """Generate an article (300-350 words)"""
        topic = self._generate_topic()
        
        prompt = f"""Write a professional article about {topic}.
        
        Requirements:
        - Length: 300-350 words exactly
        - Format: Well-structured with paragraphs
        - Tone: Professional, informative, engaging
        - Content: Include relevant examples and practical insights
        - Structure: Introduction, main points, conclusion
        
        Article:"""
        
        system_prompt = """You are a technical writer creating high-quality articles about technology topics.
        Your writing should be clear, concise, and informative. Always aim for 300-350 words."""
        
        self.logger.info(f"Generating article about: {topic}")
        article = self.generate_with_llm(prompt, system_prompt)
        
        if not article:
            self.logger.error("Failed to generate article")
            return None, None
        
        # Count words
        word_count = len(article.split())
        
        # Ensure word count is in range
        if word_count < 300:
            # Add more content
            additional_prompt = f"The following article is only {word_count} words. Please expand it to 320-350 words while maintaining quality:\n\n{article}"
            article = self.generate_with_llm(additional_prompt, system_prompt)
        elif word_count > 350:
            # Truncate intelligently (keep sentences)
            sentences = article.split('. ')
            truncated = []
            current_count = 0
            for sentence in sentences:
                sentence_words = len(sentence.split())
                if current_count + sentence_words <= 330:
                    truncated.append(sentence)
                    current_count += sentence_words
                else:
                    break
            article = '. '.join(truncated) + '.'
        
        # Create filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_topic = "".join(c for c in topic.lower() if c.isalnum() or c == ' ').replace(' ', '_')[:50]
        filename = f"articles/{safe_topic}_{timestamp}.md"
        
        # Format the article with metadata
        formatted_article = f"""# {topic}

*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
*Word count: {len(article.split())}*

---

{article}

---
*This article was automatically generated by an AI agent.*
"""
        
        self.logger.info(f"Generated article: {filename} ({len(formatted_article.split())} words)")
        return formatted_article, filename
    
    async def health_check(self) -> dict:
        """Extended health check for content agent"""
        base_health = super().health_check()
        return {
            **base_health,
            "topics_available": len(self.topics),
            "sample_topic": random.choice(self.topics) if self.topics else None
        }